import pandas as pd

# 定義題目數據
quiz_data = [
    # 簡單題 (10題)
    {
        'id': 1,
        'question': '在Python中，以下哪種數據類型是不可變的(immutable)？',
        'option_a': 'list',
        'option_b': 'dictionary',
        'option_c': 'tuple',
        'answer': 'c',
        'category': 'Python基礎',
        'difficulty': '簡單',
        'knowledge_point': '數據類型特性',
        'question_type': '概念題',
        'chapter': '基本數據類型'
    },
    {
        'id': 2,
        'question': '以下哪個是Python中用於註釋多行代碼的正確語法？',
        'option_a': '/* 註釋內容 */',
        'option_b': '""" 註釋內容 """',
        'option_c': '// 註釋內容',
        'answer': 'b',
        'category': 'Python基礎',
        'difficulty': '簡單',
        'knowledge_point': '語法基礎',
        'question_type': '語法題',
        'chapter': '基礎語法'
    },
    {
        'id': 3,
        'question': 'NumPy庫的主要數據結構是什麼？',
        'option_a': 'DataFrame',
        'option_b': 'ndarray',
        'option_c': 'Series',
        'answer': 'b',
        'category': 'NumPy',
        'difficulty': '簡單',
        'knowledge_point': 'NumPy基本概念',
        'question_type': '概念題',
        'chapter': 'NumPy基礎'
    },
    {
        'id': 4,
        'question': '以下哪個函數用於創建NumPy數組？',
        'option_a': 'np.array()',
        'option_b': 'np.matrix()',
        'option_c': 'np.dataframe()',
        'answer': 'a',
        'category': 'NumPy',
        'difficulty': '簡單',
        'knowledge_point': 'NumPy創建數組',
        'question_type': '函數應用題',
        'chapter': 'NumPy基礎'
    },
    {
        'id': 5,
        'question': '在Python中，以下哪個運算符用於取餘數？',
        'option_a': '/',
        'option_b': '//',
        'option_c': '%',
        'answer': 'c',
        'category': 'Python基礎',
        'difficulty': '簡單',
        'knowledge_point': '運算符',
        'question_type': '語法題',
        'chapter': '運算符與表達式'
    },
    {
        'id': 6,
        'question': '以下哪個不是Python的合法變量名？',
        'option_a': 'my_var',
        'option_b': '_count',
        'option_c': '2data',
        'answer': 'c',
        'category': 'Python基礎',
        'difficulty': '簡單',
        'knowledge_point': '變量命名規則',
        'question_type': '語法題',
        'chapter': '變量與數據類型'
    },
    {
        'id': 7,
        'question': 'NumPy中，以下哪個函數用於生成0到1之間的隨機數？',
        'option_a': 'np.random.rand()',
        'option_b': 'np.random.randn()',
        'option_c': 'np.random.randint()',
        'answer': 'a',
        'category': 'NumPy',
        'difficulty': '簡單',
        'knowledge_point': 'NumPy隨機數生成',
        'question_type': '函數應用題',
        'chapter': 'NumPy隨機數'
    },
    {
        'id': 8,
        'question': '在Python中，以下哪個語句用於導入NumPy庫並使用np作為別名？',
        'option_a': 'import numpy',
        'option_b': 'import numpy as np',
        'option_c': 'from numpy import *',
        'answer': 'b',
        'category': 'Python基礎',
        'difficulty': '簡單',
        'knowledge_point': '模塊導入',
        'question_type': '語法題',
        'chapter': '模塊與包'
    },
    {
        'id': 9,
        'question': '以下哪個NumPy函數用於計算數組的平均值？',
        'option_a': 'np.average()',
        'option_b': 'np.mean()',
        'option_c': 'np.median()',
        'answer': 'b',
        'category': 'NumPy',
        'difficulty': '簡單',
        'knowledge_point': 'NumPy統計函數',
        'question_type': '函數應用題',
        'chapter': 'NumPy統計操作'
    },
    {
        'id': 10,
        'question': '在Python中，以下哪個語句會產生錯誤？',
        'option_a': 'x = 1 + 2',
        'option_b': 'x = 1 + "2"',
        'option_c': 'x = "1" + "2"',
        'answer': 'b',
        'category': 'Python基礎',
        'difficulty': '簡單',
        'knowledge_point': '數據類型操作',
        'question_type': '語法題',
        'chapter': '基本數據類型'
    },
    
    # 中等題 (10題)
    {
        'id': 11,
        'question': '以下代碼的輸出是什麼？\n\nx = [1, 2, 3]\ny = x\ny.append(4)\nprint(x)',
        'option_a': '[1, 2, 3]',
        'option_b': '[1, 2, 3, 4]',
        'option_c': '[1, 2, 3, [4]]',
        'answer': 'b',
        'category': 'Python基礎',
        'difficulty': '中等',
        'knowledge_point': '可變對象引用',
        'question_type': '代碼執行題',
        'chapter': '對象與引用'
    },
    {
        'id': 12,
        'question': '以下NumPy代碼的輸出是什麼？\n\nimport numpy as np\na = np.array([1, 2, 3])\nprint(a * 2)',
        'option_a': '[1, 2, 3, 1, 2, 3]',
        'option_b': '[2, 4, 6]',
        'option_c': '[1, 1, 2, 2, 3, 3]',
        'answer': 'b',
        'category': 'NumPy',
        'difficulty': '中等',
        'knowledge_point': 'NumPy向量化運算',
        'question_type': '代碼執行題',
        'chapter': 'NumPy運算'
    },
    {
        'id': 13,
        'question': '關於Python列表推導式，以下代碼的輸出是什麼？\n\nresult = [x**2 for x in range(5) if x % 2 == 0]\nprint(result)',
        'option_a': '[0, 4, 16]',
        'option_b': '[0, 1, 4, 9, 16]',
        'option_c': '[0, 2, 4]',
        'answer': 'a',
        'category': 'Python基礎',
        'difficulty': '中等',
        'knowledge_point': '列表推導式',
        'question_type': '代碼執行題',
        'chapter': '高級數據結構'
    },
    {
        'id': 14,
        'question': '在NumPy中，以下哪個操作會改變原始數組的形狀而不創建新數組？',
        'option_a': 'np.reshape(a, (2, 3))',
        'option_b': 'a.reshape(2, 3)',
        'option_c': 'a.shape = (2, 3)',
        'answer': 'c',
        'category': 'NumPy',
        'difficulty': '中等',
        'knowledge_point': 'NumPy形狀操作',
        'question_type': '概念題',
        'chapter': 'NumPy數組操作'
    },
    {
        'id': 15,
        'question': '以下Python代碼的輸出是什麼？\n\ndef func(a, b=[]):\n    b.append(a)\n    return b\n\nprint(func(1))\nprint(func(2))',
        'option_a': '[1] [2]',
        'option_b': '[1] [1, 2]',
        'option_c': '[1, 2] [1, 2]',
        'answer': 'b',
        'category': 'Python基礎',
        'difficulty': '中等',
        'knowledge_point': '函數默認參數陷阱',
        'question_type': '代碼執行題',
        'chapter': '函數進階'
    },
    {
        'id': 16,
        'question': '在NumPy中，以下哪個函數用於沿指定軸連接數組？',
        'option_a': 'np.append()',
        'option_b': 'np.concatenate()',
        'option_c': 'np.stack()',
        'answer': 'b',
        'category': 'NumPy',
        'difficulty': '中等',
        'knowledge_point': 'NumPy數組連接',
        'question_type': '函數應用題',
        'chapter': 'NumPy數組操作'
    },
    {
        'id': 17,
        'question': '以下代碼的輸出是什麼？\n\nimport numpy as np\na = np.array([1, 2, 3, 4])\nb = a[1:3]\nb[0] = 10\nprint(a)',
        'option_a': '[1, 2, 3, 4]',
        'option_b': '[1, 10, 3, 4]',
        'option_c': '[1, 10, 10, 4]',
        'answer': 'b',
        'category': 'NumPy',
        'difficulty': '中等',
        'knowledge_point': 'NumPy視圖與副本',
        'question_type': '代碼執行題',
        'chapter': 'NumPy數據訪問'
    },
    {
        'id': 18,
        'question': '在Python中，以下哪個是裝飾器的正確用法？',
        'option_a': '@decorator\ndef func():\n    pass',
        'option_b': 'def func():\n    @decorator\n    pass',
        'option_c': 'def func():\n    pass\n@decorator(func)',
        'answer': 'a',
        'category': 'Python基礎',
        'difficulty': '中等',
        'knowledge_point': '裝飾器',
        'question_type': '語法題',
        'chapter': '函數進階'
    },
    {
        'id': 19,
        'question': '以下NumPy代碼的輸出是什麼？\n\nimport numpy as np\na = np.array([[1, 2], [3, 4]])\nprint(a.sum(axis=0))',
        'option_a': '[3, 7]',
        'option_b': '[4, 6]',
        'option_c': '10',
        'answer': 'b',
        'category': 'NumPy',
        'difficulty': '中等',
        'knowledge_point': 'NumPy軸操作',
        'question_type': '代碼執行題',
        'chapter': 'NumPy統計操作'
    },
    {
        'id': 20,
        'question': '以下關於Python生成器表達式和列表推導式的描述，哪個是正確的？',
        'option_a': '生成器表達式使用[]，列表推導式使用()',
        'option_b': '生成器表達式使用()，列表推導式使用[]',
        'option_c': '兩者語法相同，都使用[]',
        'answer': 'b',
        'category': 'Python基礎',
        'difficulty': '中等',
        'knowledge_point': '生成器與列表推導式',
        'question_type': '概念題',
        'chapter': '高級數據結構'
    },
    
    # 困難題 (10題)
    {
        'id': 21,
        'question': '以下Python代碼的輸出是什麼？\n\nclass A:\n    x = 1\n    \nclass B(A):\n    pass\n    \nclass C(A):\n    x = 2\n    \nclass D(B, C):\n    pass\n    \nprint(D.x)',
        'option_a': '1',
        'option_b': '2',
        'option_c': '錯誤',
        'answer': 'b',
        'category': 'Python基礎',
        'difficulty': '困難',
        'knowledge_point': '多重繼承與MRO',
        'question_type': '代碼執行題',
        'chapter': '面向對象高級'
    },
    {
        'id': 22,
        'question': '以下NumPy代碼的輸出是什麼？\n\nimport numpy as np\na = np.array([1, 2, 3])\nb = np.array([4, 5, 6])\nc = a @ b\nprint(c)',
        'option_a': '[4, 10, 18]',
        'option_b': '32',
        'option_c': '錯誤',
        'answer': 'b',
        'category': 'NumPy',
        'difficulty': '困難',
        'knowledge_point': 'NumPy矩陣運算',
        'question_type': '代碼執行題',
        'chapter': 'NumPy線性代數'
    },
    {
        'id': 23,
        'question': '在NumPy中，以下代碼會產生什麼結果？\n\nimport numpy as np\na = np.zeros((3, 3))\nb = a.view()\nb[0, 0] = 99\nc = a.copy()\nc[1, 1] = 88\nprint(a[0, 0], a[1, 1])',
        'option_a': '0.0 0.0',
        'option_b': '99.0 0.0',
        'option_c': '99.0 88.0',
        'answer': 'b',
        'category': 'NumPy',
        'difficulty': '困難',
        'knowledge_point': 'NumPy視圖與副本',
        'question_type': '代碼執行題',
        'chapter': 'NumPy數據訪問'
    },
    {
        'id': 24,
        'question': '以下Python代碼的輸出是什麼？\n\ndef make_counter():\n    count = 0\n    def counter():\n        nonlocal count\n        count += 1\n        return count\n    return counter\n\nc1 = make_counter()\nc2 = make_counter()\nprint(c1(), c1(), c2())',
        'option_a': '1 2 1',
        'option_b': '1 1 1',
        'option_c': '1 2 3',
        'answer': 'a',
        'category': 'Python基礎',
        'difficulty': '困難',
        'knowledge_point': '閉包與作用域',
        'question_type': '代碼執行題',
        'chapter': '函數進階'
    },
    {
        'id': 25,
        'question': '以下NumPy代碼的輸出是什麼？\n\nimport numpy as np\na = np.array([1, 2, 3, 4])\nb = a.reshape(2, 2)\nc = b.T\nprint(c[0, 1])',
        'option_a': '1',
        'option_b': '2',
        'option_c': '3',
        'answer': 'c',
        'category': 'NumPy',
        'difficulty': '困難',
        'knowledge_point': 'NumPy形狀轉換與轉置',
        'question_type': '代碼執行題',
        'chapter': 'NumPy數組操作'
    },
    {
        'id': 26,
        'question': '以下Python代碼的輸出是什麼？\n\nclass Meta(type):\n    def __new__(cls, name, bases, dct):\n        dct["x"] = 42\n        return super().__new__(cls, name, bases, dct)\n\nclass A(metaclass=Meta):\n    pass\n\nprint(A.x)',
        'option_a': 'None',
        'option_b': '42',
        'option_c': '錯誤',
        'answer': 'b',
        'category': 'Python基礎',
        'difficulty': '困難',
        'knowledge_point': '元類',
        'question_type': '代碼執行題',
        'chapter': '面向對象高級'
    },
    {
        'id': 27,
        'question': '以下NumPy代碼的輸出是什麼？\n\nimport numpy as np\na = np.array([1, 2, 3, 4])\nmask = np.array([True, False, True, False])\nprint(a[mask].sum())',
        'option_a': '4',
        'option_b': '6',
        'option_c': '10',
        'answer': 'a',
        'category': 'NumPy',
        'difficulty': '困難',
        'knowledge_point': 'NumPy布爾索引',
        'question_type': '代碼執行題',
        'chapter': 'NumPy索引與切片'
    },
    {
        'id': 28,
        'question': '以下Python代碼的輸出是什麼？\n\nfrom functools import lru_cache\n\n@lru_cache(maxsize=None)\ndef fib(n):\n    if n < 2:\n        return n\n    return fib(n-1) + fib(n-2)\n\nprint(fib(30))',
        'option_a': '832040',
        'option_b': '832041',
        'option_c': '832042',
        'answer': 'a',
        'category': 'Python基礎',
        'difficulty': '困難',
        'knowledge_point': '記憶化與裝飾器',
        'question_type': '代碼執行題',
        'chapter': '函數進階'
    },
    {
        'id': 29,
        'question': '以下NumPy代碼的輸出是什麼？\n\nimport numpy as np\na = np.arange(10)\nprint(np.where((a > 5) & (a < 8))[0])',
        'option_a': '[6, 7]',
        'option_b': '[6, 7, 8]',
        'option_c': '[6 7]',
        'answer': 'c',
        'category': 'NumPy',
        'difficulty': '困難',
        'knowledge_point': 'NumPy條件索引',
        'question_type': '代碼執行題',
        'chapter': 'NumPy索引與切片'
    },
    {
        'id': 30,
        'question': '以下關於NumPy的廣播機制(Broadcasting)的描述，哪個是錯誤的？',
        'option_a': '廣播允許不同形狀的數組進行算術運算',
        'option_b': '廣播總是從尾部維度開始比較',
        'option_c': '廣播要求兩個數組的維度必須完全相同',
        'answer': 'c',
        'category': 'NumPy',
        'difficulty': '困難',
        'knowledge_point': 'NumPy廣播機制',
        'question_type': '概念題',
        'chapter': 'NumPy高級特性'
    }
]

# 創建 DataFrame
df = pd.DataFrame(quiz_data)

# 保存為 CSV 檔案
df.to_csv('quiz.csv', index=False, encoding='utf-8-sig')

print("python_numpy_quiz.csv 已成功創建！")
